# Generated by Django 5.1.15 on 2026-07-02 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='المُعرّف (slug)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_published', models.BooleanField(default=True, verbose_name='منشورة')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('eyebrow_ar', models.CharField(blank=True, max_length=120, verbose_name='العنوان الفرعي (عربي)')),
                ('eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='العنوان الفرعي (إنجليزي)')),
                ('sector_ar', models.CharField(blank=True, max_length=160, verbose_name='القطاع (عربي)')),
                ('sector_en', models.CharField(blank=True, max_length=160, verbose_name='القطاع (إنجليزي)')),
                ('logo', models.ImageField(blank=True, upload_to='companies/logos/', verbose_name='شعار الشركة')),
                ('hero_image', models.ImageField(blank=True, upload_to='companies/hero/', verbose_name='صورة الواجهة')),
                ('hero_cta_ar', models.CharField(blank=True, max_length=80, verbose_name='زر الواجهة (عربي)')),
                ('hero_cta_en', models.CharField(blank=True, max_length=80, verbose_name='زر الواجهة (إنجليزي)')),
                ('hero_cta_href', models.CharField(default='#systems', max_length=80, verbose_name='رابط زر الواجهة')),
                ('about_paragraph_ar', models.TextField(blank=True, verbose_name='نبذة (عربي)')),
                ('about_paragraph_en', models.TextField(blank=True, verbose_name='نبذة (إنجليزي)')),
                ('about_bullets_ar', models.TextField(blank=True, verbose_name='نقاط النبذة (عربي، سطر لكل نقطة)')),
                ('about_bullets_en', models.TextField(blank=True, verbose_name='نقاط النبذة (إنجليزي، سطر لكل نقطة)')),
                ('contact_phone', models.CharField(blank=True, max_length=40, verbose_name='هاتف التواصل')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد التواصل')),
                ('contact_website', models.CharField(blank=True, max_length=120, verbose_name='الموقع (نص)')),
                ('contact_website_url', models.URLField(blank=True, verbose_name='رابط الموقع')),
                ('contact_offices_ar', models.TextField(blank=True, verbose_name='المكاتب (عربي، سطر لكل مكتب)')),
                ('contact_offices_en', models.TextField(blank=True, verbose_name='المكاتب (إنجليزي، سطر لكل مكتب)')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم المجموعة (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='اسم المجموعة (إنجليزي)')),
                ('short', models.CharField(default='APS', max_length=20, verbose_name='الاختصار')),
                ('phone', models.CharField(max_length=40, verbose_name='الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.CharField(blank=True, max_length=120, verbose_name='الموقع (نص)')),
                ('website_url', models.URLField(blank=True, verbose_name='رابط الموقع')),
                ('location_ar', models.CharField(blank=True, max_length=200, verbose_name='الموقع الجغرافي (عربي)')),
                ('location_en', models.CharField(blank=True, max_length=200, verbose_name='الموقع الجغرافي (إنجليزي)')),
                ('logo', models.ImageField(blank=True, upload_to='group/', verbose_name='الشعار (الهيدر)')),
                ('logo_footer', models.ImageField(blank=True, upload_to='group/', verbose_name='الشعار (الفوتر - أبيض)')),
            ],
            options={
                'verbose_name': 'هوية المجموعة',
                'verbose_name_plural': 'هوية المجموعة',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('sector_ar', models.CharField(blank=True, max_length=160, verbose_name='القطاع/الجهة (عربي)')),
                ('sector_en', models.CharField(blank=True, max_length=160, verbose_name='القطاع/الجهة (إنجليزي)')),
                ('image', models.ImageField(blank=True, upload_to='companies/projects/', verbose_name='الصورة')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('value', models.CharField(max_length=20, verbose_name='القيمة')),
                ('suffix', models.CharField(blank=True, max_length=10, verbose_name='اللاحقة')),
                ('label_ar', models.CharField(max_length=120, verbose_name='الوصف (عربي)')),
                ('label_en', models.CharField(blank=True, max_length=120, verbose_name='الوصف (إنجليزي)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='website.company')),
            ],
            options={
                'verbose_name': 'رقم/حقيقة',
                'verbose_name_plural': 'الأرقام والحقائق',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuidingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_ar', models.CharField(blank=True, max_length=120, verbose_name='العنوان الفرعي (عربي)')),
                ('eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='العنوان الفرعي (إنجليزي)')),
                ('heading_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربي)')),
                ('heading_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guiding_section', to='website.company')),
            ],
            options={
                'verbose_name': 'قسم المبادئ التوجيهية',
                'verbose_name_plural': 'أقسام المبادئ التوجيهية',
            },
        ),
        migrations.CreateModel(
            name='GuidingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='الأيقونة')),
                ('title_ar', models.CharField(max_length=160, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=160, verbose_name='العنوان (إنجليزي)')),
                ('text_ar', models.TextField(verbose_name='النص (عربي)')),
                ('text_en', models.TextField(blank=True, verbose_name='النص (إنجليزي)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.guidingsection')),
            ],
            options={
                'verbose_name': 'عنصر مبدأ توجيهي',
                'verbose_name_plural': 'عناصر المبادئ التوجيهية',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_ar', models.CharField(blank=True, max_length=120, verbose_name='العنوان الفرعي (عربي)')),
                ('eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='العنوان الفرعي (إنجليزي)')),
                ('heading_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربي)')),
                ('heading_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('subtitle_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('subtitle_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_section', to='website.company')),
            ],
            options={
                'verbose_name': 'قسم دورة الحياة',
                'verbose_name_plural': 'أقسام دورة الحياة',
            },
        ),
        migrations.CreateModel(
            name='LifecyclePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('no', models.CharField(blank=True, max_length=8, verbose_name='الرقم')),
                ('title_ar', models.CharField(max_length=160, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=160, verbose_name='العنوان (إنجليزي)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='website.lifecyclesection')),
            ],
            options={
                'verbose_name': 'مرحلة',
                'verbose_name_plural': 'مراحل دورة الحياة',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('title_ar', models.CharField(max_length=160, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=160, verbose_name='العنوان (إنجليزي)')),
                ('text_ar', models.TextField(verbose_name='النص (عربي)')),
                ('text_en', models.TextField(blank=True, verbose_name='النص (إنجليزي)')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='website.lifecyclephase')),
            ],
            options={
                'verbose_name': 'خطوة',
                'verbose_name_plural': 'خطوات المراحل',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_ar', models.CharField(blank=True, max_length=120, verbose_name='العنوان الفرعي (عربي)')),
                ('eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='العنوان الفرعي (إنجليزي)')),
                ('heading_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربي)')),
                ('heading_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('subtitle_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('subtitle_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partners_section', to='website.company')),
            ],
            options={
                'verbose_name': 'قسم الشركاء',
                'verbose_name_plural': 'أقسام الشركاء',
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='اسم الشريك')),
                ('image', models.ImageField(blank=True, upload_to='companies/partners/', verbose_name='الشعار')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='website.partnerssection')),
            ],
            options={
                'verbose_name': 'شعار شريك',
                'verbose_name_plural': 'شعارات الشركاء',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='الأيقونة')),
                ('label_ar', models.CharField(max_length=120, verbose_name='التسمية (عربي)')),
                ('label_en', models.CharField(blank=True, max_length=120, verbose_name='التسمية (إنجليزي)')),
                ('value_ar', models.CharField(max_length=160, verbose_name='القيمة (عربي)')),
                ('value_en', models.CharField(blank=True, max_length=160, verbose_name='القيمة (إنجليزي)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='website.project')),
            ],
            options={
                'verbose_name': 'تفصيل مشروع',
                'verbose_name_plural': 'تفاصيل المشاريع',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailed', models.BooleanField(default=False, verbose_name='بطاقات تفصيلية')),
                ('eyebrow_ar', models.CharField(blank=True, max_length=120, verbose_name='العنوان الفرعي (عربي)')),
                ('eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='العنوان الفرعي (إنجليزي)')),
                ('heading_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربي)')),
                ('heading_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('subtitle_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('subtitle_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projects_section', to='website.company')),
            ],
            options={
                'verbose_name': 'قسم المشاريع',
                'verbose_name_plural': 'أقسام المشاريع',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.projectssection'),
        ),
        migrations.CreateModel(
            name='SystemsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('tabs', 'تبويبات'), ('grid', 'شبكة')], default='grid', max_length=8, verbose_name='العرض')),
                ('eyebrow_ar', models.CharField(blank=True, max_length=120, verbose_name='العنوان الفرعي (عربي)')),
                ('eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='العنوان الفرعي (إنجليزي)')),
                ('heading_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربي)')),
                ('heading_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('subtitle_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('subtitle_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='systems_section', to='website.company')),
            ],
            options={
                'verbose_name': 'قسم الأنظمة والحلول',
                'verbose_name_plural': 'أقسام الأنظمة والحلول',
            },
        ),
        migrations.CreateModel(
            name='SystemTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='الأيقونة')),
                ('title_ar', models.CharField(max_length=160, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=160, verbose_name='العنوان (إنجليزي)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='website.systemssection')),
            ],
            options={
                'verbose_name': 'تبويب أنظمة',
                'verbose_name_plural': 'تبويبات الأنظمة',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SystemItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='الاسم (إنجليزي)')),
                ('image', models.ImageField(blank=True, upload_to='companies/systems/', verbose_name='الصورة')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.systemssection')),
                ('tab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.systemtab')),
            ],
            options={
                'verbose_name': 'عنصر نظام',
                'verbose_name_plural': 'عناصر الأنظمة',
                'ordering': ['order', 'id'],
            },
        ),
    ]
