# Generated by Django 5.1.15 on 2026-07-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_eyebrow_ar', models.CharField(default='ابقَ على تواصل', max_length=120, verbose_name='سطر علوي (عربي)')),
                ('cta_eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (إنجليزي)')),
                ('cta_title_ar', models.CharField(default='تواصل مع فريقنا للاستفسارات', max_length=200, verbose_name='العنوان (عربي)')),
                ('cta_title_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('cta_title_hl_ar', models.CharField(default='والدعم', max_length=80, verbose_name='الكلمة المميّزة (عربي)')),
                ('cta_title_hl_en', models.CharField(blank=True, max_length=80, verbose_name='الكلمة المميّزة (إنجليزي)')),
                ('cta_subtitle_ar', models.TextField(default='يستجيب فريقنا بسرعة بحلولٍ احترافية مصمّمة خصيصاً لتلبية احتياجاتك الكهروميكانيكية والصناعية.', verbose_name='الوصف (عربي)')),
                ('cta_subtitle_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
                ('cta_button_ar', models.CharField(default='تواصل معنا', max_length=80, verbose_name='نص الزر (عربي)')),
                ('cta_button_en', models.CharField(blank=True, max_length=80, verbose_name='نص الزر (إنجليزي)')),
                ('cta_offices_label_ar', models.CharField(default='مكاتبنا:', max_length=40, verbose_name='كلمة "مكاتبنا" (عربي)')),
                ('cta_offices_label_en', models.CharField(blank=True, max_length=40, verbose_name='كلمة "مكاتبنا" (إنجليزي)')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
