# Generated by Django 5.1.15 on 2026-07-02 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title_ar', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO (عربي)')),
                ('seo_title_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO (إنجليزي)')),
                ('seo_description_ar', models.TextField(blank=True, verbose_name='وصف SEO (عربي)')),
                ('seo_description_en', models.TextField(blank=True, verbose_name='وصف SEO (إنجليزي)')),
                ('seo_image', models.CharField(default='images/about/hero.jpg', max_length=200, verbose_name='صورة SEO (مسار)')),
                ('intro_eyebrow_ar', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (عربي)')),
                ('intro_eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (إنجليزي)')),
                ('intro_title_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربي)')),
                ('intro_title_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('intro_lead_ar', models.TextField(blank=True, verbose_name='المقدمة (عربي)')),
                ('intro_lead_en', models.TextField(blank=True, verbose_name='المقدمة (إنجليزي)')),
                ('intro_bullets_ar', models.TextField(blank=True, verbose_name='نقاط (عربي، سطر لكل نقطة)')),
                ('intro_bullets_en', models.TextField(blank=True, verbose_name='نقاط (إنجليزي، سطر لكل نقطة)')),
                ('intro_cta_ar', models.CharField(blank=True, max_length=80, verbose_name='نص الزر (عربي)')),
                ('intro_cta_en', models.CharField(blank=True, max_length=80, verbose_name='نص الزر (إنجليزي)')),
                ('intro_image', models.ImageField(blank=True, upload_to='about/', verbose_name='صورة المقدمة')),
                ('guiding_eyebrow_ar', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (عربي)')),
                ('guiding_eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (إنجليزي)')),
                ('guiding_heading_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربي)')),
                ('guiding_heading_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('principles_eyebrow_ar', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (عربي)')),
                ('principles_eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (إنجليزي)')),
                ('principles_heading_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربي)')),
                ('principles_heading_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('principles_subtitle_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('principles_subtitle_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
                ('hse_eyebrow_ar', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (عربي)')),
                ('hse_eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (إنجليزي)')),
                ('hse_heading_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربي)')),
                ('hse_heading_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('hse_subtitle_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('hse_subtitle_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
            ],
            options={
                'verbose_name': 'صفحة من نحن',
                'verbose_name_plural': 'صفحة من نحن',
            },
        ),
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('guiding', 'الرؤية والرسالة'), ('principles', 'مبادئ العمل'), ('hse', 'الصحة والسلامة')], max_length=12, verbose_name='القسم')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='الأيقونة')),
                ('title_ar', models.CharField(max_length=160, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=160, verbose_name='العنوان (إنجليزي)')),
                ('text_ar', models.TextField(verbose_name='النص (عربي)')),
                ('text_en', models.TextField(blank=True, verbose_name='النص (إنجليزي)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.aboutpage')),
            ],
            options={
                'verbose_name': 'عنصر (من نحن)',
                'verbose_name_plural': 'عناصر من نحن',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('value', models.CharField(max_length=20, verbose_name='القيمة')),
                ('suffix', models.CharField(blank=True, max_length=10, verbose_name='اللاحقة')),
                ('label_ar', models.CharField(max_length=120, verbose_name='الوصف (عربي)')),
                ('label_en', models.CharField(blank=True, max_length=120, verbose_name='الوصف (إنجليزي)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='website.aboutpage')),
            ],
            options={
                'verbose_name': 'رقم (من نحن)',
                'verbose_name_plural': 'أرقام من نحن',
                'ordering': ['order', 'id'],
            },
        ),
    ]
