# Generated by Django 5.1.15 on 2026-07-02 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_aboutpage_aboutitem_aboutfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='الأيقونة')),
                ('title_ar', models.CharField(max_length=160, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=160, verbose_name='العنوان (إنجليزي)')),
            ],
            options={
                'verbose_name': 'فئة FAQ',
                'verbose_name_plural': 'فئات FAQ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FaqPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title_ar', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO (عربي)')),
                ('seo_title_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO (إنجليزي)')),
                ('seo_description_ar', models.TextField(blank=True, verbose_name='وصف SEO (عربي)')),
                ('seo_description_en', models.TextField(blank=True, verbose_name='وصف SEO (إنجليزي)')),
                ('hero_eyebrow_ar', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (عربي)')),
                ('hero_eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (إنجليزي)')),
                ('hero_title_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربي)')),
                ('hero_title_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('hero_subtitle_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('hero_subtitle_en', models.TextField(blank=True, verbose_name='الوصف (إنجليزي)')),
            ],
            options={
                'verbose_name': 'صفحة الأسئلة الشائعة',
                'verbose_name_plural': 'صفحة الأسئلة الشائعة',
            },
        ),
        migrations.CreateModel(
            name='FaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('question_ar', models.CharField(max_length=300, verbose_name='السؤال (عربي)')),
                ('question_en', models.CharField(blank=True, max_length=300, verbose_name='السؤال (إنجليزي)')),
                ('answer_ar', models.TextField(verbose_name='الجواب (عربي)')),
                ('answer_en', models.TextField(blank=True, verbose_name='الجواب (إنجليزي)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.faqcategory')),
            ],
            options={
                'verbose_name': 'سؤال FAQ',
                'verbose_name_plural': 'أسئلة FAQ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='website.faqpage'),
        ),
        migrations.CreateModel(
            name='FaqStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('value', models.CharField(max_length=20, verbose_name='القيمة')),
                ('suffix', models.CharField(blank=True, max_length=10, verbose_name='اللاحقة')),
                ('label_ar', models.CharField(max_length=120, verbose_name='الوصف (عربي)')),
                ('label_en', models.CharField(blank=True, max_length=120, verbose_name='الوصف (إنجليزي)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='website.faqpage')),
            ],
            options={
                'verbose_name': 'رقم (FAQ)',
                'verbose_name_plural': 'أرقام FAQ',
                'ordering': ['order', 'id'],
            },
        ),
    ]
