# Generated by Django 5.1.15 on 2026-07-02 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_faqcategory_faqpage_faqitem_faqcategory_page_faqstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title_ar', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO (عربي)')),
                ('seo_title_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO (إنجليزي)')),
                ('seo_description_ar', models.TextField(blank=True, verbose_name='وصف SEO (عربي)')),
                ('seo_description_en', models.TextField(blank=True, verbose_name='وصف SEO (إنجليزي)')),
                ('eyebrow_ar', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (عربي)')),
                ('eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (إنجليزي)')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('lead_ar', models.TextField(blank=True, verbose_name='المقدمة (عربي)')),
                ('lead_en', models.TextField(blank=True, verbose_name='المقدمة (إنجليزي)')),
                ('subjects_ar', models.TextField(blank=True, verbose_name='مواضيع الرسالة (عربي، سطر لكل موضوع)')),
                ('subjects_en', models.TextField(blank=True, verbose_name='مواضيع الرسالة (إنجليزي، سطر لكل موضوع)')),
                ('offices_heading_ar', models.CharField(blank=True, max_length=200, verbose_name='عنوان المكاتب (عربي)')),
                ('offices_heading_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان المكاتب (إنجليزي)')),
                ('offices_subtitle_ar', models.TextField(blank=True, verbose_name='وصف المكاتب (عربي)')),
                ('offices_subtitle_en', models.TextField(blank=True, verbose_name='وصف المكاتب (إنجليزي)')),
            ],
            options={
                'verbose_name': 'صفحة تواصل معنا',
                'verbose_name_plural': 'صفحة تواصل معنا',
            },
        ),
        migrations.CreateModel(
            name='ContactOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('name_ar', models.CharField(max_length=120, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='الاسم (إنجليزي)')),
                ('tag_ar', models.CharField(blank=True, max_length=80, verbose_name='الوسم (عربي)')),
                ('tag_en', models.CharField(blank=True, max_length=80, verbose_name='الوسم (إنجليزي)')),
                ('address_ar', models.TextField(blank=True, verbose_name='العنوان (عربي)')),
                ('address_en', models.TextField(blank=True, verbose_name='العنوان (إنجليزي)')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('map_query', models.CharField(blank=True, max_length=200, verbose_name='استعلام الخريطة')),
                ('is_hq', models.BooleanField(default=False, verbose_name='المقر الرئيسي')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='website.contactpage')),
            ],
            options={
                'verbose_name': 'مكتب',
                'verbose_name_plural': 'المكاتب',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('icon', models.CharField(blank=True, max_length=40, verbose_name='الأيقونة')),
                ('label_ar', models.CharField(max_length=120, verbose_name='التسمية (عربي)')),
                ('label_en', models.CharField(blank=True, max_length=120, verbose_name='التسمية (إنجليزي)')),
                ('value_ar', models.CharField(max_length=200, verbose_name='القيمة (عربي)')),
                ('value_en', models.CharField(blank=True, max_length=200, verbose_name='القيمة (إنجليزي)')),
                ('href', models.CharField(blank=True, max_length=200, verbose_name='الرابط (tel:/mailto:)')),
                ('ltr', models.BooleanField(default=False, verbose_name='اتجاه LTR (أرقام/لاتيني)')),
                ('note_ar', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة (عربي)')),
                ('note_en', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة (إنجليزي)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='website.contactpage')),
            ],
            options={
                'verbose_name': 'قناة تواصل',
                'verbose_name_plural': 'قنوات التواصل',
                'ordering': ['order', 'id'],
            },
        ),
    ]
