# Generated by Django 5.1.15 on 2026-07-02 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contactpage_contactoffice_contactchannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title_ar', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO (عربي)')),
                ('seo_title_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO (إنجليزي)')),
                ('seo_description_ar', models.TextField(blank=True, verbose_name='وصف SEO (عربي)')),
                ('seo_description_en', models.TextField(blank=True, verbose_name='وصف SEO (إنجليزي)')),
                ('seo_image', models.CharField(default='images/hero/hero-industrial.jpg', max_length=200, verbose_name='صورة SEO (مسار)')),
                ('intro_eyebrow_ar', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (عربي)')),
                ('intro_eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='سطر علوي (إنجليزي)')),
                ('intro_title_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربي)')),
                ('intro_title_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان (إنجليزي)')),
                ('intro_lead_ar', models.TextField(blank=True, verbose_name='المقدمة (عربي)')),
                ('intro_lead_en', models.TextField(blank=True, verbose_name='المقدمة (إنجليزي)')),
                ('group_eyebrow_ar', models.CharField(default='الشركة القابضة', max_length=120, verbose_name='وسم المجموعة القابضة (عربي)')),
                ('group_eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='وسم المجموعة القابضة (إنجليزي)')),
                ('group_name_ar', models.CharField(default='مجموعة APS', max_length=160, verbose_name='اسم المجموعة (عربي)')),
                ('group_name_en', models.CharField(blank=True, max_length=160, verbose_name='اسم المجموعة (إنجليزي)')),
                ('sub_eyebrow_ar', models.CharField(default='شركة تابعة', max_length=120, verbose_name='وسم الشركات التابعة (عربي)')),
                ('sub_eyebrow_en', models.CharField(blank=True, max_length=120, verbose_name='وسم الشركات التابعة (إنجليزي)')),
            ],
            options={
                'verbose_name': 'صفحة الشركاء',
                'verbose_name_plural': 'صفحة الشركاء',
            },
        ),
        migrations.CreateModel(
            name='PartnersFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('value', models.CharField(max_length=20, verbose_name='القيمة')),
                ('suffix', models.CharField(blank=True, max_length=10, verbose_name='اللاحقة')),
                ('label_ar', models.CharField(max_length=120, verbose_name='الوصف (عربي)')),
                ('label_en', models.CharField(blank=True, max_length=120, verbose_name='الوصف (إنجليزي)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='website.partnerspage')),
            ],
            options={
                'verbose_name': 'رقم (الشركاء)',
                'verbose_name_plural': 'أرقام الشركاء',
                'ordering': ['order', 'id'],
            },
        ),
    ]
