# Generated by Django 5.1.15 on 2026-07-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_partnerspage_partnersfact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='الهاتف')),
                ('company', models.CharField(blank=True, max_length=160, verbose_name='الشركة')),
                ('subjects', models.CharField(blank=True, max_length=300, verbose_name='المواضيع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'صندوق الوارد',
                'ordering': ['-created_at'],
            },
        ),
    ]
