# Generated by Django 5.1.15 on 2026-07-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutitem',
            name='icon_image',
            field=models.ImageField(blank=True, upload_to='about/icons/', verbose_name='أيقونة مرفوعة (PNG/SVG)'),
        ),
        migrations.AlterField(
            model_name='aboutitem',
            name='icon',
            field=models.CharField(blank=True, max_length=40, verbose_name='اسم أيقونة جاهزة'),
        ),
    ]
