# Generated by Django 5.1.15 on 2026-07-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_aboutitem_icon_image_alter_aboutitem_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='intro_cta_href',
            field=models.CharField(blank=True, default='/#subsidiaries', max_length=200, verbose_name='رابط الزر'),
        ),
    ]
