# Generated by Django 5.1.15 on 2026-07-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_aboutpage_intro_cta_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactchannel',
            name='icon_image',
            field=models.ImageField(blank=True, upload_to='contact/icons/', verbose_name='أيقونة مرفوعة (PNG/SVG)'),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='icon_image',
            field=models.ImageField(blank=True, upload_to='faq/icons/', verbose_name='أيقونة مرفوعة (PNG/SVG)'),
        ),
        migrations.AddField(
            model_name='guidingitem',
            name='icon_image',
            field=models.ImageField(blank=True, upload_to='companies/guiding/icons/', verbose_name='أيقونة مرفوعة (PNG/SVG)'),
        ),
        migrations.AddField(
            model_name='systemtab',
            name='icon_image',
            field=models.ImageField(blank=True, upload_to='companies/systems/icons/', verbose_name='أيقونة مرفوعة (PNG/SVG)'),
        ),
        migrations.AlterField(
            model_name='contactchannel',
            name='icon',
            field=models.CharField(blank=True, max_length=40, verbose_name='اسم أيقونة جاهزة'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=40, verbose_name='اسم أيقونة جاهزة'),
        ),
        migrations.AlterField(
            model_name='guidingitem',
            name='icon',
            field=models.CharField(blank=True, max_length=40, verbose_name='اسم أيقونة جاهزة'),
        ),
        migrations.AlterField(
            model_name='systemtab',
            name='icon',
            field=models.CharField(blank=True, max_length=40, verbose_name='اسم أيقونة جاهزة'),
        ),
    ]
