# Generated by Django 5.1.15 on 2026-07-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_contactchannel_icon_image_faqcategory_icon_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutfact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='aboutitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='companyfact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='contactchannel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='contactoffice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='faqitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='faqpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='faqstat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='guidingitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='guidingsection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='lifecyclephase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='lifecyclesection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='lifecyclestep',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='partnersfact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='partnerspage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='partnerssection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='projectssection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='systemitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='systemssection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='systemtab',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='آخر تحديث'),
        ),
    ]
